name: Pull request changes
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pass_directly_tests:
    name: "Run cleanup tests pass directly via envs"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - &checkout_step
        name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          submodules: "recursive"
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create files
        id: files
        run: |
          empty=""
          not_exists=".not_exists"
          first=".first_file"
          second="$(realpath .)"
          second="${second}/second-file"

          echo "first" > "$first"
          echo "second" > "$second"
          
          echo "first=${first}" >> $GITHUB_OUTPUT
          echo "second=${second}" >> $GITHUB_OUTPUT
          echo "empty=${empty}" >> $GITHUB_OUTPUT
          echo "not_exists=${not_exists}" >> $GITHUB_OUTPUT
      
      - name: Create dirs
        id: dirs
        run: |
          empty_dir="empty"
          first=".first_dir"
          second="$(realpath .)"
          second="${second}/second-dir"
          second_sub="${second}/sub-dir"

          for dd in "$empty_dir" "$first" "$second" "$second_sub"; do
            mkdir -p "$dd"
          done

          echo "first" > "${first}/first.txt"
          echo "second" > "${second}/second.txt"
          echo "third" > "${second}/third.txt"
          echo "four" > "${second_sub}/third.txt"
          
          echo "first=${first}" >> $GITHUB_OUTPUT
          echo "second=${second}" >> $GITHUB_OUTPUT
          echo "empty_dir=${empty_dir}" >> $GITHUB_OUTPUT
    
      - name: Run action
        uses: ./
        env:
          CLEANUP_PATH_FILE_FIRST: ${{ steps.files.outputs.first }}
          CLEANUP_PATH_FILE_SECOND: ${{ steps.files.outputs.second }}
          CLEANUP_PATH_FILE_EMPTY: ${{ steps.files.outputs.empty }}
          CLEANUP_PATH_FILE_NOT_EXISTS: ${{ steps.files.outputs.not_exists }}
          CLEANUP_PATH_FILE_NOT_EXISTS_IN_OUTPUTS: ${{ steps.files.outputs.no_output }}
          CLEANUP_PATH_DIR_FIRST: ${{ steps.dirs.outputs.first }}
          CLEANUP_PATH_DIR_SECOND: ${{ steps.dirs.outputs.second }}
          CLEANUP_PATH_DIR_EMPTY: ${{ steps.dirs.outputs.empty_dir }}
          CLEANUP_PATH_DIR_EMPTY_IN_OUTPUTS: ${{ steps.dirs.outputs.output_no }}

  pass_via_github_env_tests:
    name: "Run cleanup tests pass via GITHUB_ENV"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - *checkout_step
      - name: Create files
        id: files
        run: |
          empty=""
          not_exists=".not_exists"
          first=".first_file"
          second="$(realpath .)"
          second="${second}/second-file"

          echo "first" > "$first"
          echo "second" > "$second"
          
          echo "CLEANUP_PATH_FILE_FIRST=${first}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_FILE_SECOND=${second}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_FILE_EMPTY=${empty}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_FILE_NOT_EXISTS=${not_exists}" >> $GITHUB_ENV
      
      - name: Create dirs
        id: dirs
        run: |
          empty_dir="empty"
          first=".first_dir"
          second="$(realpath .)"
          second="${second}/second-dir"
          second_sub="${second}/sub-dir"

          for dd in "$empty_dir" "$first" "$second" "$second_sub"; do
            mkdir -p "$dd"
          done

          echo "first" > "${first}/first.txt"
          echo "second" > "${second}/second.txt"
          echo "third" > "${second}/third.txt"
          echo "four" > "${second_sub}/third.txt"
          
          echo "CLEANUP_PATH_DIR_FIRST=${first}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_DIR_SECOND=${second}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_DIR_EMPTY=${empty_dir}" >> $GITHUB_ENV
    
      - name: Run action
        uses: ./ 
  fail:
    name: "Run cleanup tests with always and fail"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - *checkout_step
      - name: Create files
        id: files
        run: |
          empty=""
          not_exists=".not_exists"
          first=".first_file"
          second="$(realpath .)"
          second="${second}/second-file"

          echo "first" > "$first"
          echo "second" > "$second"
          
          echo "CLEANUP_PATH_FILE_FIRST=${first}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_FILE_SECOND=${second}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_FILE_EMPTY=${empty}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_FILE_NOT_EXISTS=${not_exists}" >> $GITHUB_ENV
      
      - name: Create dirs
        id: dirs
        run: |
          empty_dir="empty"
          first=".first_dir"
          second="$(realpath .)"
          second="${second}/second-dir"
          second_sub="${second}/sub-dir"

          for dd in "$empty_dir" "$first" "$second" "$second_sub"; do
            mkdir -p "$dd"
          done

          echo "first" > "${first}/first.txt"
          echo "second" > "${second}/second.txt"
          echo "third" > "${second}/third.txt"
          echo "four" > "${second_sub}/third.txt"
          
          echo "CLEANUP_PATH_DIR_FIRST=${first}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_DIR_SECOND=${second}" >> $GITHUB_ENV
          echo "CLEANUP_PATH_DIR_EMPTY=${empty_dir}" >> $GITHUB_ENV
      
      - name: Do error
        run: |
          echo "Error!"
          exit 1

      - name: Run action
        if: always()
        uses: ./
